<?php
/**
 * Page Title Tab For Theme Option.
 *
 * @package H-Code
 */
?>
<?php
$accordian_content_start = $wc_category_title_wrapper = $wc_category_page_title_premade_style = $wc_category_header_subtitle = $wc_category_title_background = $wc_category_title_parallax_effect = $wc_category_page_title_show_breadcrumb = $wc_category_page_title_show_separator = $accordian_content_end = '';
if(class_exists( 'WooCommerce' )){
    $accordian_content_start = array(
        'id'        => 'opt-accordion-begin-page-title',
        'type'      => 'accordion',
        'title'     => esc_html__('WooCommerce Categories Page Title Settings', 'H-Code' ),
        'subtitle'  => esc_html__('Set woocommerce categories, brands and shop page title settings.', 'H-Code' ),
        'position'  => 'start',
    );
    $wc_category_title_wrapper = array(
        'id'       => 'hcode_enable_wc_category_title_wrapper',
        'type'     => 'switch',
        'title'    => esc_html__('Enable Title', 'H-Code'),
        'default'  => true,
        'subtitle' => esc_html__('If on, a title will display in category page', 'H-Code'),
        '2'       => 'On',
        '0'      => 'Off',
    );
    $wc_category_page_title_premade_style = array(
        'id'       => 'hcode_wc_category_page_title_premade_style',
        'type'     => 'select',
        'title'    => esc_html__( 'Title Style', 'H-Code' ),
        'options'  => array(esc_html__('', 'H-Code') => esc_html__('Please select style', 'H-Code'),
                       'title-wc-style' => esc_html__('Title Shop Style', 'H-Code'),
                       'title-white' => esc_html__('Title White', 'H-Code'),
                       'title-gray' => esc_html__('Title Gray', 'H-Code'),
                       'title-dark-gray' => esc_html__('Title Dark Gray', 'H-Code'),
                       'title-black' => esc_html__('Title Black', 'H-Code'),
                       'title-with-image' => esc_html__('Title With Image', 'H-Code'),
                       'title-large' => esc_html__('Title Large', 'H-Code'),
                       'title-large-without-overlay' => esc_html__('Title Large Without Overlay', 'H-Code'),
                       'title-small-white' => esc_html__('Title Small White', 'H-Code'),
                       'title-small-gray' => esc_html__('Title Small Gray', 'H-Code'),
                       'title-small-dark-gray' => esc_html__('Title Small Dark Gray', 'H-Code'),
                       'title-small-black' => esc_html__('Title Small Black', 'H-Code'),
                       'title-center-align' => esc_html__('Title Center Align', 'H-Code'),
                      ),
        'subtitle' => esc_html__( 'Choose style for the title', 'H-Code' ),
        'default'  => 'title-wc-style',
    );
    $wc_category_header_subtitle = array(
        'id' => 'hcode_wc_category_header_subtitle',
        'type' => 'text',
        'title' => esc_html__('Subtitle', 'H-Code'),
        'default' => '',
        'required'  => array('hcode_wc_category_page_title_premade_style', '=', array('title-white','title-gray','title-dark-gray','title-black','title-with-image','title-large','title-large-without-overlay','title-center-align','title-wc-style')),
    );
    $wc_category_title_background = array(
        'id'       => 'hcode_wc_category_title_background',
        'type'     => 'media',
        'preview'  => true,
        'url'      => true,  
        'title'    => esc_html__( 'Title Background Image', 'H-Code' ),
        'subtitle' => esc_html__('Recommended image size (1920px X 700px) for better result.', 'H-Code'),
        'required'  => array('hcode_wc_category_page_title_premade_style', '=', array('title-with-image','title-large','title-large-without-overlay','title-wc-style')),
    );
    $wc_category_title_parallax_effect = array(
        'id'       => 'hcode_wc_category_title_parallax_effect',
        'type'     => 'select',
        'title'    => esc_html__( 'Parallax effect', 'H-Code' ),
        'options'  => array('no-effect' => esc_html__('No Effect', 'H-Code'),
                  'parallax1' => esc_html__('parallax-effect-1', 'H-Code'),
                  'parallax2' => esc_html__('parallax-effect-2', 'H-Code'),
                  'parallax3' => esc_html__('parallax-effect-3', 'H-Code'),
                  'parallax4' => esc_html__('parallax-effect-4', 'H-Code'),
                  'parallax5' => esc_html__('parallax-effect-5', 'H-Code'),
                  'parallax6' => esc_html__('parallax-effect-6', 'H-Code'),
                  'parallax7' => esc_html__('parallax-effect-7', 'H-Code'),
                  'parallax8' => esc_html__('parallax-effect-8', 'H-Code'),
                  'parallax9' => esc_html__('parallax-effect-9', 'H-Code'),
                  'parallax10' => esc_html__('parallax-effect-10', 'H-Code'),
                  'parallax11' => esc_html__('parallax-effect-11', 'H-Code'),
                  'parallax12' => esc_html__('parallax-effect-12', 'H-Code')
                 ),
        'subtitle' => esc_html__( 'Choose parallax effect', 'H-Code' ),
        'required'  => array('hcode_wc_category_page_title_premade_style', '=', array('title-with-image','title-large','title-large-without-overlay')),
    );
    $wc_category_page_title_show_breadcrumb = array(
        'id'       => 'hcode_wc_category_page_title_show_breadcrumb',
        'type'     => 'switch',
        'title'    => esc_html__('Enable Breadcrumb', 'H-Code'),
        'default'  => true,
        'subtitle' => esc_html__('If on, breadcrumb will display in title section', 'H-Code'),
        '1'       => 'Yes',
        '2'      => 'No',
        'required'  => array('hcode_wc_category_page_title_premade_style', '=', array('title-white','title-gray','title-dark-gray','title-black','title-with-image','title-small-white','title-small-gray','title-small-dark-gray','title-small-black','title-wc-style')),
    );
    $wc_category_page_title_show_separator = array(
        'id'       => 'hcode_wc_category_page_title_show_separator',
        'type'     => 'switch',
        'title'    => esc_html__('Enable Separator', 'H-Code'),
        'default'  => false,
        'subtitle' => esc_html__('If on, separator will display in title section', 'H-Code'),
        '1'       => 'On',
        '0'      => 'Off',
        'required'  => array('hcode_wc_category_page_title_premade_style', '=', array('title-white','title-gray','title-dark-gray','title-black','title-with-image','title-large','title-large-without-overlay','title-small-white','title-small-gray','title-small-dark-gray','title-small-black','title-center-align')),
    );
    $accordian_content_end = array(
            'id'        => 'opt-accordion-end-general',
            'type'      => 'accordion',
            'position'  => 'end'
        );
}


$this->sections[] = array(
    'icon' => 'el-icon-website',
    'title' => esc_html__('Page Title', 'H-Code'),
    'fields' => array(
    	  array(
            'id'       => 'hcode_enable_title_wrapper',
            'type'     => 'switch',
            'title'    => esc_html__('Enable Title', 'H-Code'),
            'default'  => true,
            'subtitle' => esc_html__('If on, a title will display in page', 'H-Code'),
            '2'       => 'On',
            '0'      => 'Off',
        ),
        array(
            'id'       => 'hcode_page_title_premade_style',
            'type'     => 'select',
            'title'    => esc_html__( 'Title Style', 'H-Code' ),
            'options'  => array(esc_html__('', 'H-Code') => esc_html__('Please select style', 'H-Code'),
                           'title-white' => esc_html__('Title White', 'H-Code'),
                           'title-gray' => esc_html__('Title Gray', 'H-Code'),
                           'title-dark-gray' => esc_html__('Title Dark Gray', 'H-Code'),
                           'title-black' => esc_html__('Title Black', 'H-Code'),
                           'title-with-image' => esc_html__('Title With Image', 'H-Code'),
                           'title-large' => esc_html__('Title Large', 'H-Code'),
                           'title-large-without-overlay' => esc_html__('Title Large Without Overlay', 'H-Code'),
                           'title-small-white' => esc_html__('Title Small White', 'H-Code'),
                           'title-small-gray' => esc_html__('Title Small Gray', 'H-Code'),
                           'title-small-dark-gray' => esc_html__('Title Small Dark Gray', 'H-Code'),
                           'title-small-black' => esc_html__('Title Small Black', 'H-Code'),
                           'title-center-align' => esc_html__('Title Center Align', 'H-Code'),
                          ),
            'subtitle' => esc_html__( 'Choose style for the title', 'H-Code' ),
            'default'  => 'title-small-gray',
        ),
        array(
          'id' => 'hcode_header_subtitle',
          'type' => 'text',
          'title' => esc_html__('Subtitle', 'H-Code'),
          'default' => '',
          'required'  => array('hcode_page_title_premade_style', '=', array('title-white','title-gray','title-dark-gray','title-black','title-with-image','title-large','title-large-without-overlay','title-center-align')),
        ),
        array(
            'id'       => 'hcode_title_background',
            'type'     => 'media',
            'preview'  => true,
            'url'      => true,  
            'title'    => esc_html__( 'Title Background Image', 'H-Code' ),
            'subtitle' => esc_html__('Recommended image size (1920px X 700px) for better result.', 'H-Code'),
            'required'  => array('hcode_page_title_premade_style', '=', array('title-with-image','title-large','title-large-without-overlay')),
        ),
        array(
            'id'       => 'hcode_title_parallax_effect',
            'type'     => 'select',
            'title'    => esc_html__( 'Parallax effect', 'H-Code' ),
            'options'  => array('no-effect' => esc_html__('No Effect', 'H-Code'),
                      'parallax1' => esc_html__('parallax-effect-1', 'H-Code'),
                      'parallax2' => esc_html__('parallax-effect-2', 'H-Code'),
                      'parallax3' => esc_html__('parallax-effect-3', 'H-Code'),
                      'parallax4' => esc_html__('parallax-effect-4', 'H-Code'),
                      'parallax5' => esc_html__('parallax-effect-5', 'H-Code'),
                      'parallax6' => esc_html__('parallax-effect-6', 'H-Code'),
                      'parallax7' => esc_html__('parallax-effect-7', 'H-Code'),
                      'parallax8' => esc_html__('parallax-effect-8', 'H-Code'),
                      'parallax9' => esc_html__('parallax-effect-9', 'H-Code'),
                      'parallax10' => esc_html__('parallax-effect-10', 'H-Code'),
                      'parallax11' => esc_html__('parallax-effect-11', 'H-Code'),
                      'parallax12' => esc_html__('parallax-effect-12', 'H-Code')
                     ),
            'subtitle' => esc_html__( 'Choose parallax effect', 'H-Code' ),
            'required'  => array('hcode_page_title_premade_style', '=', array('title-with-image','title-large','title-large-without-overlay')),
        ),
        array(
            'id'       => 'hcode_page_title_show_breadcrumb',
            'type'     => 'switch',
            'title'    => esc_html__('Enable Breadcrumb', 'H-Code'),
            'default'  => true,
            'subtitle' => esc_html__('If on, breadcrumb will display in title section', 'H-Code'),
            '1'       => 'Yes',
            '2'      => 'No',
            'required'  => array('hcode_page_title_premade_style', '=', array('title-white','title-gray','title-dark-gray','title-black','title-with-image','title-small-white','title-small-gray','title-small-dark-gray','title-small-black')),
        ),
        array(
            'id'       => 'hcode_page_title_show_separator',
            'type'     => 'switch',
            'title'    => esc_html__('Enable Separator', 'H-Code'),
            'default'  => false,
            'subtitle' => esc_html__('If on, separator will display in title section', 'H-Code'),
            '1'       => 'On',
            '0'      => 'Off',
            'required'  => array('hcode_page_title_premade_style', '=', array('title-white','title-gray','title-dark-gray','title-black','title-with-image','title-large','title-large-without-overlay','title-small-white','title-small-gray','title-small-dark-gray','title-small-black','title-center-align')),
        ),
        array(
            'id'        => 'opt-accordion-begin-page-title',
            'type'      => 'accordion',
            'title'     => esc_html__('Default Posts / Blog Page Title Settings', 'H-Code' ),
            'subtitle'  => esc_html__('Set default / blog page title settings.', 'H-Code' ),
            'position'  => 'start',
        ),
        array(
            'id'       => 'hcode_enable_blog_title_wrapper',
            'type'     => 'switch',
            'title'    => esc_html__('Enable Title', 'H-Code'),
            'default'  => true,
            'subtitle' => esc_html__('If on, a title will display in category page', 'H-Code'),
            '2'       => 'On',
            '0'      => 'Off',
        ),
        array(
            'id'       => 'hcode_blog_page_title_premade_style',
            'type'     => 'select',
            'title'    => esc_html__( 'Title Style', 'H-Code' ),
            'options'  => array(esc_html__('', 'H-Code') => esc_html__('Please select style', 'H-Code'),
                           'title-white' => esc_html__('Title White', 'H-Code'),
                           'title-gray' => esc_html__('Title Gray', 'H-Code'),
                           'title-dark-gray' => esc_html__('Title Dark Gray', 'H-Code'),
                           'title-black' => esc_html__('Title Black', 'H-Code'),
                           'title-with-image' => esc_html__('Title With Image', 'H-Code'),
                           'title-large' => esc_html__('Title Large', 'H-Code'),
                           'title-large-without-overlay' => esc_html__('Title Large Without Overlay', 'H-Code'),
                           'title-small-white' => esc_html__('Title Small White', 'H-Code'),
                           'title-small-gray' => esc_html__('Title Small Gray', 'H-Code'),
                           'title-small-dark-gray' => esc_html__('Title Small Dark Gray', 'H-Code'),
                           'title-small-black' => esc_html__('Title Small Black', 'H-Code'),
                           'title-center-align' => esc_html__('Title Center Align', 'H-Code'),
                          ),
            'subtitle' => esc_html__( 'Choose style for the title', 'H-Code' ),
            'default'  => 'title-small-gray',
        ),
        array(
          'id' => 'hcode_blog_header_subtitle',
          'type' => 'text',
          'title' => esc_html__('Subtitle', 'H-Code'),
          'default' => '',
          'required'  => array('hcode_blog_page_title_premade_style', '=', array('title-white','title-gray','title-dark-gray','title-black','title-with-image','title-large','title-large-without-overlay','title-center-align')),
        ),
        array(
            'id'       => 'hcode_blog_title_background',
            'type'     => 'media',
            'preview'  => true,
            'url'      => true,  
            'title'    => esc_html__( 'Title Background Image', 'H-Code' ),
            'subtitle' => esc_html__('Recommended image size (1920px X 700px) for better result.', 'H-Code'),
            'required'  => array('hcode_blog_page_title_premade_style', '=', array('title-with-image','title-large','title-large-without-overlay')),
        ),
        array(
            'id'       => 'hcode_blog_title_parallax_effect',
            'type'     => 'select',
            'title'    => esc_html__( 'Parallax effect', 'H-Code' ),
            'options'  => array('no-effect' => esc_html__('No Effect', 'H-Code'),
                      'parallax1' => esc_html__('parallax-effect-1', 'H-Code'),
                      'parallax2' => esc_html__('parallax-effect-2', 'H-Code'),
                      'parallax3' => esc_html__('parallax-effect-3', 'H-Code'),
                      'parallax4' => esc_html__('parallax-effect-4', 'H-Code'),
                      'parallax5' => esc_html__('parallax-effect-5', 'H-Code'),
                      'parallax6' => esc_html__('parallax-effect-6', 'H-Code'),
                      'parallax7' => esc_html__('parallax-effect-7', 'H-Code'),
                      'parallax8' => esc_html__('parallax-effect-8', 'H-Code'),
                      'parallax9' => esc_html__('parallax-effect-9', 'H-Code'),
                      'parallax10' => esc_html__('parallax-effect-10', 'H-Code'),
                      'parallax11' => esc_html__('parallax-effect-11', 'H-Code'),
                      'parallax12' => esc_html__('parallax-effect-12', 'H-Code')
                     ),
            'subtitle' => esc_html__( 'Choose parallax effect', 'H-Code' ),
            'required'  => array('hcode_blog_page_title_premade_style', '=', array('title-with-image','title-large','title-large-without-overlay')),
        ),
        array(
            'id'       => 'hcode_blog_page_title_show_breadcrumb',
            'type'     => 'switch',
            'title'    => esc_html__('Enable Breadcrumb', 'H-Code'),
            'default'  => true,
            'subtitle' => esc_html__('If on, breadcrumb will display in title section', 'H-Code'),
            '1'       => 'Yes',
            '2'      => 'No',
            'required'  => array('hcode_blog_page_title_premade_style', '=', array('title-white','title-gray','title-dark-gray','title-black','title-with-image','title-small-white','title-small-gray','title-small-dark-gray','title-small-black')),
        ),
        array(
            'id'       => 'hcode_blog_page_title_show_separator',
            'type'     => 'switch',
            'title'    => esc_html__('Enable Separator', 'H-Code'),
            'default'  => false,
            'subtitle' => esc_html__('If on, separator will display in title section', 'H-Code'),
            '1'       => 'On',
            '0'      => 'Off',
            'required'  => array('hcode_blog_page_title_premade_style', '=', array('title-white','title-gray','title-dark-gray','title-black','title-with-image','title-large','title-large-without-overlay','title-small-white','title-small-gray','title-small-dark-gray','title-small-black','title-center-align')),
        ),
        array(
            'id'        => 'opt-accordion-end-page-title',
            'type'      => 'accordion',
            'position'  => 'end'
        ),
        array(
            'id'        => 'opt-accordion-begin-page-title',
            'type'      => 'accordion',
            'title'     => esc_html__('Archive Page Title Settings', 'H-Code' ),
            'subtitle'  => esc_html__('Set archive, categories, tags, author and search page title settings.', 'H-Code' ),
            'position'  => 'start',
        ),
        array(
            'id'       => 'hcode_enable_archive_title_wrapper',
            'type'     => 'switch',
            'title'    => esc_html__('Enable Title', 'H-Code'),
            'default'  => true,
            'subtitle' => esc_html__('If on, a title will display in archive page', 'H-Code'),
            '2'       => 'On',
            '0'      => 'Off',
        ),
        array(
            'id'       => 'hcode_archive_page_title_premade_style',
            'type'     => 'select',
            'title'    => esc_html__( 'Title Style', 'H-Code' ),
            'options'  => array(esc_html__('', 'H-Code') => esc_html__('Please select style', 'H-Code'),
                           'title-white' => esc_html__('Title White', 'H-Code'),
                           'title-gray' => esc_html__('Title Gray', 'H-Code'),
                           'title-dark-gray' => esc_html__('Title Dark Gray', 'H-Code'),
                           'title-black' => esc_html__('Title Black', 'H-Code'),
                           'title-with-image' => esc_html__('Title With Image', 'H-Code'),
                           'title-large' => esc_html__('Title Large', 'H-Code'),
                           'title-large-without-overlay' => esc_html__('Title Large Without Overlay', 'H-Code'),
                           'title-small-white' => esc_html__('Title Small White', 'H-Code'),
                           'title-small-gray' => esc_html__('Title Small Gray', 'H-Code'),
                           'title-small-dark-gray' => esc_html__('Title Small Dark Gray', 'H-Code'),
                           'title-small-black' => esc_html__('Title Small Black', 'H-Code'),
                           'title-center-align' => esc_html__('Title Center Align', 'H-Code'),
                          ),
            'subtitle' => esc_html__( 'Choose style for the title', 'H-Code' ),
            'default'  => 'title-small-gray',
        ),
        array(
          'id' => 'hcode_archive_header_subtitle',
          'type' => 'text',
          'title' => esc_html__('Subtitle', 'H-Code'),
          'default' => '',
          'required'  => array('hcode_archive_page_title_premade_style', '=', array('title-white','title-gray','title-dark-gray','title-black','title-with-image','title-large','title-large-without-overlay','title-center-align')),
        ),
        array(
            'id'       => 'hcode_archive_title_background',
            'type'     => 'media',
            'preview'  => true,
            'url'      => true,  
            'title'    => esc_html__( 'Title Background Image', 'H-Code' ),
            'subtitle' => esc_html__('Recommended image size (1920px X 700px) for better result.', 'H-Code'),
            'required'  => array('hcode_archive_page_title_premade_style', '=', array('title-with-image','title-large','title-large-without-overlay')),
        ),
        array(
            'id'       => 'hcode_archive_title_parallax_effect',
            'type'     => 'select',
            'title'    => esc_html__( 'Parallax effect', 'H-Code' ),
            'options'  => array('no-effect' => esc_html__('No Effect', 'H-Code'),
                      'parallax1' => esc_html__('parallax-effect-1', 'H-Code'),
                      'parallax2' => esc_html__('parallax-effect-2', 'H-Code'),
                      'parallax3' => esc_html__('parallax-effect-3', 'H-Code'),
                      'parallax4' => esc_html__('parallax-effect-4', 'H-Code'),
                      'parallax5' => esc_html__('parallax-effect-5', 'H-Code'),
                      'parallax6' => esc_html__('parallax-effect-6', 'H-Code'),
                      'parallax7' => esc_html__('parallax-effect-7', 'H-Code'),
                      'parallax8' => esc_html__('parallax-effect-8', 'H-Code'),
                      'parallax9' => esc_html__('parallax-effect-9', 'H-Code'),
                      'parallax10' => esc_html__('parallax-effect-10', 'H-Code'),
                      'parallax11' => esc_html__('parallax-effect-11', 'H-Code'),
                      'parallax12' => esc_html__('parallax-effect-12', 'H-Code')
                     ),
            'subtitle' => esc_html__( 'Choose parallax effect', 'H-Code' ),
            'required'  => array('hcode_archive_page_title_premade_style', '=', array('title-with-image','title-large','title-large-without-overlay')),
        ),
        array(
            'id'       => 'hcode_archive_page_title_show_breadcrumb',
            'type'     => 'switch',
            'title'    => esc_html__('Enable Breadcrumb', 'H-Code'),
            'default'  => true,
            'subtitle' => esc_html__('If on, breadcrumb will display in title section', 'H-Code'),
            '1'       => 'Yes',
            '2'      => 'No',
            'required'  => array('hcode_archive_page_title_premade_style', '=', array('title-white','title-gray','title-dark-gray','title-black','title-with-image','title-small-white','title-small-gray','title-small-dark-gray','title-small-black')),
        ),
        array(
            'id'       => 'hcode_archive_page_title_show_separator',
            'type'     => 'switch',
            'title'    => esc_html__('Enable Separator', 'H-Code'),
            'default'  => false,
            'subtitle' => esc_html__('If on, separator will display in title section', 'H-Code'),
            '1'       => 'On',
            '0'      => 'Off',
            'required'  => array('hcode_archive_page_title_premade_style', '=', array('title-white','title-gray','title-dark-gray','title-black','title-with-image','title-large','title-large-without-overlay','title-small-white','title-small-gray','title-small-dark-gray','title-small-black','title-center-align')),
        ),
        array(
            'id'        => 'opt-accordion-end-page-title',
            'type'      => 'accordion',
            'position'  => 'end'
        ),
        $accordian_content_start,
        $wc_category_title_wrapper,
        $wc_category_page_title_premade_style,
        $wc_category_header_subtitle,
        $wc_category_title_background,
        $wc_category_title_parallax_effect,
        $wc_category_page_title_show_breadcrumb,
        $wc_category_page_title_show_separator,
        $accordian_content_end,
    )
);
?>